### ISSUE TITLE
Foundry Quality Enhancer bug

### ISSUE THREAD

**Issue by folknor** [Xeinaemm/Factorio-Tileable-Factories#3]
Hi!

There's two misplaced inserters and a misplaced requester chest in the center of the Foundry Quality Enhancer blueprint.

Thank you!

**Comment by Xeinaemm** [comment]
Thanks for reporting an issue. Fixed in version [v0.29.1](https://github.com/Xeinaemm/Factorio-Tileable-Factories/releases/tag/v0.29.1)
